# Generated by Django 4.0.5 on 2022-07-08 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sendmessagesmodel',
            options={'ordering': ['SM_SubscriptionAmount']},
        ),
        migrations.RemoveField(
            model_name='sendmessagesmodel',
            name='SM_User',
        ),
    ]
