# Generated by Django 4.0.5 on 2022-07-08 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_alter_sendmessagesmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sendmessagesmodel',
            options={},
        ),
        migrations.RemoveField(
            model_name='sendmessagesmodel',
            name='SM_Notes',
        ),
    ]
