# Generated by Django 4.0.5 on 2022-07-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0003_alter_sendmessagesmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendmessagesmodel',
            name='SM_Email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
