# Generated by Django 4.0.5 on 2022-07-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0004_sendmessagesmodel_sm_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendmessagesmodel',
            name='SM_Mobil',
            field=models.CharField(db_index=True, default=1, max_length=17, verbose_name='الجوال'),
            preserve_default=False,
        ),
    ]
