# Generated by Django 4.0.5 on 2022-07-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0005_sendmessagesmodel_sm_mobil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendmessagesmodel',
            name='SM_Email',
            field=models.EmailField(default='fayiez@outlook.com', max_length=254),
        ),
    ]
