# Generated by Django 4.0.5 on 2022-07-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0006_alter_sendmessagesmodel_sm_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendmessagesmodel',
            name='SM_Mobil',
            field=models.CharField(db_index=True, default='+966506361923', max_length=17, verbose_name='الجوال'),
        ),
    ]
