# Generated by Django 4.0.5 on 2022-07-25 15:13

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalsmodel',
            name='P_Mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, region=None, unique=True, verbose_name='الجوال'),
        ),
    ]
