# Generated by Django 4.0.5 on 2022-06-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financialstatements_model',
            old_name='FS_NumberShares',
            new_name='FS_NumberPaymentsDue',
        ),
        migrations.RenameField(
            model_name='financialstatements_model',
            old_name='FS_ShareValue',
            new_name='FS_SubscriptionAmount',
        ),
        migrations.RemoveField(
            model_name='datesreceivingpayments_model',
            name='DRP_DeservedAmount',
        ),
        migrations.RemoveField(
            model_name='datesreceivingpayments_model',
            name='DRP_NumberShares',
        ),
        migrations.AlterField(
            model_name='datesreceivingpayments_model',
            name='DRP_DateReceivigPayments_Short',
            field=models.DateField(blank=True, db_index=True, help_text='Required Field', null=True, verbose_name='تاريخ استلام اﻷسهم/المشاركات/المستحقات'),
        ),
        migrations.AlterField(
            model_name='datesreceivingpayments_model',
            name='DRP_Notes',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='الملاحظات'),
        ),
    ]
