# Generated by Django 4.0.5 on 2022-06-23 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_fs_numbershares_financialstatements_model_fs_numberpaymentsdue_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalfile_model',
            old_name='FF_Slug',
            new_name='PF_Slug',
        ),
    ]
