# Generated by Django 4.0.5 on 2022-06-23 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_rename_ff_slug_personalfile_model_pf_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatesReceivingMoneyPayments_MODEL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DRP_DateReceivigMoneyPayments_Long', models.CharField(choices=[('01-January__Jumada Al-Awwal-(05)', '01-January__Jumada Al-Awwal-(05)'), ('02-February_Jumada Al-Thani-(06)', '02-February_Jumada Al-Thani-(06)'), ('03-March______________Rajab-(07)', '03-March______________Rajab-(07)'), ('04-April_____________Shaban-(08)', '04-April_____________Shaban-(08)'), ('05-May______________Ramadan-(09)', '05-May______________Ramadan-(09)'), ('06-June_____________Shawwal-(10)', '06-June_____________Shawwal-(10)'), ('07-July__________Dhul-Qadah-(11)', '07-July__________Dhul-Qadah-(11)'), ('08-August_______Dhul-Hijjah-(12)', '08-August_______Dhul-Hijjah-(12)'), ('09-September_______Muharram-(01)', '09-September_______Muharram-(01)'), ('10-October____________Safar-(02)', '10-October____________Safar-(02)'), ('11-November___Rabi Al-Awwal-(03)', '11-November___Rabi Al-Awwal-(03)'), ('12-December___Rabi Al-Thani-(04)', '12-December___Rabi Al-Thani-(04)'), ('00-All_______________Al-Kol-(00)', '00-All_______________Al-Kol-(00)')], db_index=True, default='Please Choose ', help_text='Required Field', max_length=50, verbose_name='موعد إستلام المال - بالشهر')),
                ('DRP_DateReceivigMoneyPayments_Short', models.DateField(blank=True, db_index=True, help_text='Required Field', null=True, verbose_name='موعد إستلام المال - بالتاريخ')),
                ('DRP_Notes', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='الملاحظات')),
                ('DRP_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='اسم المشترك')),
            ],
            options={
                'ordering': ['DRP_DateReceivigMoneyPayments_Long'],
            },
        ),
        migrations.DeleteModel(
            name='DatesReceivingPayments_MODEL',
        ),
    ]
