# Generated by Django 4.0.5 on 2022-06-24 15:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_datesreceivingmoneypayments_model_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PersonalFile_MODEL',
            new_name='ProfileMODEL',
        ),
        migrations.AlterModelOptions(
            name='profilemodel',
            options={'ordering': ['P_User']},
        ),
        migrations.RenameField(
            model_name='profilemodel',
            old_name='PF_Address',
            new_name='P_Address',
        ),
        migrations.RenameField(
            model_name='profilemodel',
            old_name='PF_Avialable',
            new_name='P_Avialable',
        ),
        migrations.RenameField(
            model_name='profilemodel',
            old_name='PF_FamilyName',
            new_name='P_FamilyName',
        ),
        migrations.RenameField(
            model_name='profilemodel',
            old_name='PF_FatherName',
            new_name='P_FatherName',
        ),
        migrations.RenameField(
            model_name='profilemodel',
            old_name='PF_FirstName',
            new_name='P_FirstName',
        ),
        migrations.RenameField(
            model_name='profilemodel',
            old_name='PF_GrandFatherName',
            new_name='P_GrandFatherName',
        ),
        migrations.RenameField(
            model_name='profilemodel',
            old_name='PF_Mobile',
            new_name='P_Mobile',
        ),
        migrations.RenameField(
            model_name='profilemodel',
            old_name='PF_Notes',
            new_name='P_Notes',
        ),
        migrations.RenameField(
            model_name='profilemodel',
            old_name='PF_Photo',
            new_name='P_Photo',
        ),
        migrations.RenameField(
            model_name='profilemodel',
            old_name='PF_Slug',
            new_name='P_Slug',
        ),
        migrations.RenameField(
            model_name='profilemodel',
            old_name='PF_User',
            new_name='P_User',
        ),
    ]
