# Generated by Django 4.0.5 on 2022-06-24 15:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_rename_personalfile_model_profilemodel_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileMODEL',
            new_name='ProfilesMODEL',
        ),
    ]
