# Generated by Django 4.0.5 on 2022-06-24 15:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0007_rename_financialstatements_model_financialstatementsmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DatesReceivingMoneyPayments_MODEL',
            new_name='DatesReceivingMoneyPaymentsMODEL',
        ),
    ]
