# Generated by Django 4.0.5 on 2022-08-06 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_personalsmodel_p_mobile_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
