# Generated by Django 4.0.5 on 2022-08-08 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0025_remove_subscribersdesiresmodel_sd_desire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribersdesiresmodel',
            name='SD_User',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='اسم المشترك'),
        ),
    ]
