# Generated by Django 4.0.5 on 2022-08-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_subscribersdesiresmodel_sd_desire_first_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribersdesiresmodel',
            name='SD_Desire_first',
            field=models.CharField(choices=[('01-January____جمادى الأولى-(05)   ', '01-January      (05)جمادى الأولى'), ('02-February___جمادى الثاني-(06)   ', '02-February     جمادى الثاني-(06)'), ('03-March______راجب-(07)           ', '03-March        رجب         -(07)'), ('04-April______شعبان-(08)          ', '04-April        شعبان       -(08)'), ('05-May________رمضان-(09)          ', '05-May          رمضان       -(09)'), ('06-June_______شوال-(10)           ', '06-June         شوال        -(10)'), ('07-July_______ذو القعدة-(11)      ', '07-July         ذو القعدة   -(11)'), ('08-August_____ذو الحجة-(12)       ', '08-August       ذو الحجة    -(12)'), ('09-September__محرم-(01)           ', '09-September    محرم        -(01)'), ('10-October____صفر-(02)            ', '10-October      صفر         -(02)'), ('11-November___ربيع الأول-(03)     ', '11-November     ربيع الأول  -(03)'), ('12-December___ربيع الثاني-(04)    ', '12-December     ربيع الثاني -(04)'), ('لم يتم تحديد اي رغبة حتى الأن-(00)', 'لم يتم تحديد اي رغبة حتى الأن-(00)')], db_index=True, default='لم يتم تحديد اي رغبة حتى الأن-(00)', help_text='Required Field', max_length=50, verbose_name='الرغبة الأولى'),
        ),
        migrations.AlterField(
            model_name='subscribersdesiresmodel',
            name='SD_Desire_second',
            field=models.CharField(choices=[('01-January____جمادى الأولى-(05)   ', '01-January      (05)جمادى الأولى'), ('02-February___جمادى الثاني-(06)   ', '02-February     جمادى الثاني-(06)'), ('03-March______راجب-(07)           ', '03-March        رجب         -(07)'), ('04-April______شعبان-(08)          ', '04-April        شعبان       -(08)'), ('05-May________رمضان-(09)          ', '05-May          رمضان       -(09)'), ('06-June_______شوال-(10)           ', '06-June         شوال        -(10)'), ('07-July_______ذو القعدة-(11)      ', '07-July         ذو القعدة   -(11)'), ('08-August_____ذو الحجة-(12)       ', '08-August       ذو الحجة    -(12)'), ('09-September__محرم-(01)           ', '09-September    محرم        -(01)'), ('10-October____صفر-(02)            ', '10-October      صفر         -(02)'), ('11-November___ربيع الأول-(03)     ', '11-November     ربيع الأول  -(03)'), ('12-December___ربيع الثاني-(04)    ', '12-December     ربيع الثاني -(04)'), ('لم يتم تحديد اي رغبة حتى الأن-(00)', 'لم يتم تحديد اي رغبة حتى الأن-(00)')], db_index=True, default='لم يتم تحديد اي رغبة حتى الأن-(00)', help_text='Required Field', max_length=50, verbose_name='الرغبة الثانية'),
        ),
        migrations.AlterField(
            model_name='subscribersdesiresmodel',
            name='SD_Desire_third',
            field=models.CharField(choices=[('01-January____جمادى الأولى-(05)   ', '01-January      (05)جمادى الأولى'), ('02-February___جمادى الثاني-(06)   ', '02-February     جمادى الثاني-(06)'), ('03-March______راجب-(07)           ', '03-March        رجب         -(07)'), ('04-April______شعبان-(08)          ', '04-April        شعبان       -(08)'), ('05-May________رمضان-(09)          ', '05-May          رمضان       -(09)'), ('06-June_______شوال-(10)           ', '06-June         شوال        -(10)'), ('07-July_______ذو القعدة-(11)      ', '07-July         ذو القعدة   -(11)'), ('08-August_____ذو الحجة-(12)       ', '08-August       ذو الحجة    -(12)'), ('09-September__محرم-(01)           ', '09-September    محرم        -(01)'), ('10-October____صفر-(02)            ', '10-October      صفر         -(02)'), ('11-November___ربيع الأول-(03)     ', '11-November     ربيع الأول  -(03)'), ('12-December___ربيع الثاني-(04)    ', '12-December     ربيع الثاني -(04)'), ('لم يتم تحديد اي رغبة حتى الأن-(00)', 'لم يتم تحديد اي رغبة حتى الأن-(00)')], db_index=True, default='لم يتم تحديد اي رغبة حتى الأن-(00)', help_text='Required Field', max_length=50, verbose_name='الرغبة الثالثة'),
        ),
    ]
