# Generated by Django 4.0.5 on 2022-08-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_alter_subscribersdesiresmodel_sd_desire_first_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datesreceivingmoneypaymentsmodel',
            name='DRMP_DateReceivingMoneyPayments_Long',
            field=models.CharField(choices=[('01-January__Jumada Al-Awwal-(05)  ', '01-January      (05)  جمادى الأولى'), ('02-February_Jumada Al-Thani-(06)  ', '02-February     جمادى الثاني  (06)'), ('03-March______________Rajab-(07)  ', '03-March        رجب           (07)'), ('04-April_____________Shaban-(08)  ', '04-April        شعبان         (08)'), ('05-May______________Ramadan-(09)  ', '05-May          رمضان         (09)'), ('06-June_____________Shawwal-(10)  ', '06-June         شوال          (10)'), ('07-July__________Dhul-Qadah-(11)  ', '07-July         ذو القعدة     (11)'), ('08-August_______Dhul-Hijjah-(12)  ', '08-August       ذو الحجة      (12)'), ('09-September_______Muharram-(01)  ', '09-September    محرم          (01)'), ('10-October____________Safar-(02)  ', '10-October      صفر           (02)'), ('11-November___Rabi Al-Awwal-(03)  ', '11-November     ربيع الأول    (03)'), ('12-December___Rabi Al-Thani-(04)  ', '12-December     ربيع الثاني   (04)'), ('The Date Has Not Yet Been Set-(00)', 'لم يتم تحديد اي رغبة حتى الأن-(00)')], db_index=True, default='The Date Has Not Yet Been Set-(00)', help_text='Required Field', max_length=50, verbose_name='موعد إستلام المال - بالشهر'),
        ),
    ]
