# Generated by Django 4.0.5 on 2022-08-11 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_alter_datesreceivingmoneypaymentsmodel_drmp_datereceivingmoneypayments_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datesreceivingmoneypaymentsmodel',
            name='DRMP_Notes',
            field=models.CharField(blank=True, db_index=True, default='-', max_length=100, null=True, verbose_name='الملاحظات'),
        ),
        migrations.AlterField(
            model_name='financialstatementsmodel',
            name='FS_Notes',
            field=models.CharField(blank=True, db_index=True, default='-', max_length=100, null=True, verbose_name='الملاحظات'),
        ),
        migrations.AlterField(
            model_name='personalsmodel',
            name='P_Notes',
            field=models.CharField(blank=True, db_index=True, default='-', max_length=100, null=True, verbose_name='الملاحظات'),
        ),
        migrations.AlterField(
            model_name='subscribersdesiresmodel',
            name='SD_Notes',
            field=models.CharField(blank=True, db_index=True, default='-', max_length=100, null=True, verbose_name='الملاحظات'),
        ),
    ]
