# Generated by Django 4.0.5 on 2022-08-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_alter_datesreceivingmoneypaymentsmodel_drmp_datereceivingmoneypayments_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datesreceivingmoneypaymentsmodel',
            name='DRMP_DateReceivingMoneyPayments_Short',
            field=models.DateField(auto_now_add=True, db_index=True, help_text='Required Field', null=True, verbose_name='موعد إستلام المال - بالتاريخ'),
        ),
    ]
