# Generated by Django 4.0.5 on 2022-08-13 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_alter_datesreceivingmoneypaymentsmodel_drmp_datereceivingmoneypayments_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datesreceivingmoneypaymentsmodel',
            name='DRMP_DateReceivingMoneyPayments_Short',
            field=models.DateField(blank=True, db_index=True, default=datetime.date.today, help_text='Required Field', null=True, verbose_name='موعد إستلام المال - بالتاريخ'),
        ),
    ]
